#version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongodb_data:/data/db

  biometria-app:
    image: biometria-api-image
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://user:1234@mongodb:27017/biometria_db?authSource=admin

volumes:
  mongodb_data: